FROM suarez123/wan22-i2v:wan22-lora-pack-20260402-001955-libx264

ENV LORA_HIGH_WEIGHT=0.5
ENV LORA_LOW_WEIGHT=0.3

COPY --from=downloads ["lowE9AB98E68AACE885.E9ax.safetensors", "/comfyui/models/loras/lowE9AB98E68AACE885.E9ax.safetensors"]
COPY --from=downloads ["highE68A93E4BD8FE8B7AA.TQSA.safetensors", "/comfyui/models/loras/highE68A93E4BD8FE8B7AA.TQSA.safetensors"]
COPY --from=downloads ["lowE68A93E4BD8FE8B7AA.XnYy.safetensors", "/comfyui/models/loras/lowE68A93E4BD8FE8B7AA.XnYy.safetensors"]
COPY --from=downloads ["E78EBBE79283High.ffNp.safetensors", "/comfyui/models/loras/E78EBBE79283High.ffNp.safetensors"]
COPY --from=downloads ["WAN-2.2-I2V-FaceDownAssUp-HIGH-v1.safetensors", "/comfyui/models/loras/WAN-2.2-I2V-FaceDownAssUp-HIGH-v1.safetensors"]
COPY --from=downloads ["WAN-2.2-I2V-FaceDownAssUp-LOW-v1.safetensors", "/comfyui/models/loras/WAN-2.2-I2V-FaceDownAssUp-LOW-v1.safetensors"]
COPY --from=downloads ["E6B7B9E6B2A1High.oNPH.safetensors", "/comfyui/models/loras/E6B7B9E6B2A1High.oNPH.safetensors"]
COPY --from=downloads ["E68993E884B890E9AB98.uiDs.safetensors", "/comfyui/models/loras/E68993E884B890E9AB98.uiDs.safetensors"]
COPY --from=downloads ["WAN2.2-FrenchKiss_HighNoise.safetensors", "/comfyui/models/loras/WAN2.2-FrenchKiss_HighNoise.safetensors"]
COPY --from=downloads ["WAN2.2-FrenchKiss_LowNoise.safetensors", "/comfyui/models/loras/WAN2.2-FrenchKiss_LowNoise.safetensors"]
COPY --from=downloads ["reverse_suspended_congress_I2V_low.safetensors", "/comfyui/models/loras/reverse_suspended_congress_I2V_low.safetensors"]
COPY --from=downloads ["reverse_suspended_congress_I2V_high.safetensors", "/comfyui/models/loras/reverse_suspended_congress_I2V_high.safetensors"]
COPY --from=downloads ["WAN-2.2-I2V-HandjobBlowjobCombo-LOW-v1.safetensors", "/comfyui/models/loras/WAN-2.2-I2V-HandjobBlowjobCombo-LOW-v1.safetensors"]
COPY --from=downloads ["WAN-2.2-I2V-HandjobBlowjobCombo-HIGH-v1.safetensors", "/comfyui/models/loras/WAN-2.2-I2V-HandjobBlowjobCombo-HIGH-v1.safetensors"]
COPY --from=downloads ["WAN-2.2-I2V-POV-Titfuck-Paizuri-LOW-v1.0.safetensors", "/comfyui/models/loras/WAN-2.2-I2V-POV-Titfuck-Paizuri-LOW-v1.0.safetensors"]
COPY --from=downloads ["WAN-2.2-I2V-POV-Titfuck-Paizuri-HIGH-v1.0.safetensors", "/comfyui/models/loras/WAN-2.2-I2V-POV-Titfuck-Paizuri-HIGH-v1.0.safetensors"]
COPY --from=downloads ["23High noise-Cumshot Aesthetics.safetensors", "/comfyui/models/loras/23High noise-Cumshot Aesthetics.safetensors"]
COPY --from=downloads ["56Low noise-Cumshot Aesthetics.safetensors", "/comfyui/models/loras/56Low noise-Cumshot Aesthetics.safetensors"]
COPY --from=downloads ["wan2.2_i2v_lownoise_pov_missionary_v1.0.safetensors", "/comfyui/models/loras/wan2.2_i2v_lownoise_pov_missionary_v1.0.safetensors"]
COPY --from=downloads ["wan2.2_i2v_highnoise_pov_missionary_v1.0.safetensors", "/comfyui/models/loras/wan2.2_i2v_highnoise_pov_missionary_v1.0.safetensors"]
COPY --from=downloads ["WAN2.2-I2V_HighNoise_I2Pee-V4.safetensors", "/comfyui/models/loras/WAN2.2-I2V_HighNoise_I2Pee-V4.safetensors"]
COPY --from=downloads ["WAN2.2-I2V_LowNoise_I2Pee-V4.safetensors", "/comfyui/models/loras/WAN2.2-I2V_LowNoise_I2Pee-V4.safetensors"]
