FROM suarez123/akuma-z-image-basic:zimage-turbo-v35-basic-waitfix2

RUN uv pip install -r /comfyui/requirements.txt

COPY handler.py /handler.py
COPY start.sh /start.sh
RUN chmod +x /start.sh

CMD ["/start.sh"]
